Repository TaskSprints/auction-front, pull requests merged in 2024-09, with the labels that each got.

#22 상세페이지[상세검색]
  src/App.tsx
  src/components/common/DetailSearch/DetailSearch.tsx
  src/components/common/MenuComponent/MenuComponent.tsx
  src/pages/DetailsPage.tsx
Labels: enhancement

#26 [설정] 관련 라이브러리 초기 설정을 위한 Package.json 구성하기.
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  netlify.toml
  package-lock.json
  package.json
  public/vite.svg
  src/app/styles/index.css
  src/app/styles/tailwind.css
  src/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.mts
Labels: enhancement

#29 axios 관련 class 작업
  package-lock.json
  package.json
  src/features/products/ui/CategoryAuction/CategoryAuction.tsx
  src/features/products/ui/CategoryAuction/CategoryAuctionCard.tsx
  src/features/products/ui/CategoryAuction/CustomArrow.tsx
  src/features/products/ui/HotAuction/AuctionInfoList.tsx
  src/features/products/ui/HotAuction/HotAuctionCard.tsx
  src/features/products/ui/category/CategoryBoardList.tsx
  src/features/products/ui/category/CategoryList.tsx
  src/index.tsx
  src/shared/index.tsx
  src/shared/requests/api-instance-client.ts
  src/shared/requests/apisInstance.ts
  src/shared/requests/products/fetchCategoryBoard.ts
  src/shared/requests/products/fetchMainCategoryLongImage.ts
  src/shared/requests/products/fetchMainCategoryPro.ts
  src/shared/requests/products/products-api-client.ts
  src/shared/store/products/products-store.ts
  src/shared/store/products/productsStore.ts
  src/shared/types/ICategoryPageBoard.ts
  src/shared/types/IMainCategoryImage.ts
  src/shared/types/ImainCategoryProducts.ts
  src/shared/types/products.ts
Labels: bug

#36 format : indent_size 수정
  .editorconfig
Labels: bug

#33 Feat: ESLint 스크립트 & Vite 초기 설정 추가
  package-lock.json
  package.json
  tsconfig.json
  vite.config.mts
Labels: enhancement

#38 Feat : Auction endpoint Api 연결 및 커스텀 훅 제작
  .editorconfig
  package.json
  src/features/auction/hooks/useAuctionQuery.tsx
  src/features/products/ui/AuctionInfo/index.tsx
  src/features/products/ui/CategoryAuction/CategoryAuction.tsx
  src/features/products/ui/HotAuction/AuctionInfoList.tsx
  src/features/products/ui/category/CategoryList.tsx
  src/pages/CategoryPage.tsx
  src/shared/api.ts
  src/shared/index.tsx
  src/shared/requests/api-instance-client.ts
  src/shared/requests/products/products-api-client.ts
  src/shared/store/products/products-store.ts
  vite.config.mts
Labels: documentation, enhancement
